export const FETCH_STATE_REQUEST="FETCH_STATE_REQUEST";

export const FETCH_STATE_SUCCESS="FETCH_STATE_SUCCESS";

export const FETCH_STATE_FAILURE="FETCH_STATE_FAILURE";

export const  SELECT_STATE="SELECT_STATE";


export const FETCH_COUNTRY_DETAIL_REQUEST="FETCH_COUNTRY_DETAIL_REQUEST"

export const FETCH_COUNTRY_DETAIL_SUCCESS="FETCH_COUNTRY_DETAIL_SUCCESS";

export const FETCH_COUNTRY_DETAIL_FAILURE="FETCH_COUNTRY_DETAIL_FAILURE"

export const ADD_POPULATION="ADD_POPULATION";